//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFThesisManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThesisManagementContext : DbContext
    {
        public ThesisManagementContext()
            : base("name=ThesisManagementContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RegisterQueue> RegisterQueues { get; set; }
        public virtual DbSet<StudentAccount> StudentAccounts { get; set; }
        public virtual DbSet<StudentGroup> StudentGroups { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<TeacherAccount> TeacherAccounts { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
    }
}
