//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFThesisManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int notification_id { get; set; }
        public string notification_title { get; set; }
        public string notification_content { get; set; }
        public Nullable<int> sender_id { get; set; }
        public Nullable<int> recipient_id { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string notification_status { get; set; }
        public string notification_type { get; set; }
        public Nullable<int> related_id { get; set; }
    }
}
