//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFThesisManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointSheetRecord
    {
        public int id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> topic_id { get; set; }
        public Nullable<double> point { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
