//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFThesisManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherAccount
    {
        public string teacher_username { get; set; }
        public string teacher_password { get; set; }
        public Nullable<int> teacher_id { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
