//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFThesisManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Topic()
        {
            this.RegisterQueues = new HashSet<RegisterQueue>();
            this.StudentGroups = new HashSet<StudentGroup>();
        }

        public Topic(int parse, string text, string s, string toString, string toString1, string text1, int i)
        {
            
        }

        public int topic_id { get; set; }
        public string topic_name { get; set; }
        public string topic_description { get; set; }
        public string topic_technology { get; set; }
        public string topic_requirement { get; set; }
        public string topic_category { get; set; }
        public Nullable<int> max_members { get; set; }
        public Nullable<int> teacher_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterQueue> RegisterQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentGroup> StudentGroups { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
